
import java.sql.ResultSet;
import javax.swing.JOptionPane;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author HP
 */
public class AccountantLogin extends javax.swing.JFrame {

    /**
     * Creates new form AccountantLogin
     */
    public AccountantLogin() {
        initComponents();
        setDefaultCloseOperation(DISPOSE_ON_CLOSE);
        setTitle("ACCOUNTANT LOGIN");
        setSize(700,500);
        setVisible(true);
        setLayout(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        name_lbl = new javax.swing.JLabel();
        password_lbl = new javax.swing.JLabel();
        title_lbl = new javax.swing.JLabel();
        name_tf = new javax.swing.JTextField();
        password_tf = new javax.swing.JPasswordField();
        login_btn = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        jLabel1.setText("jLabel1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        name_lbl.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        name_lbl.setText("ACCOUNTANT NAME");
        getContentPane().add(name_lbl);
        name_lbl.setBounds(30, 160, 210, 50);

        password_lbl.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        password_lbl.setText("PASSWORD");
        getContentPane().add(password_lbl);
        password_lbl.setBounds(30, 260, 140, 50);

        title_lbl.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        title_lbl.setText("ACCOUNTANT LOGIN");
        title_lbl.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        getContentPane().add(title_lbl);
        title_lbl.setBounds(70, 30, 410, 50);

        name_tf.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        getContentPane().add(name_tf);
        name_tf.setBounds(280, 170, 230, 40);

        password_tf.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        getContentPane().add(password_tf);
        password_tf.setBounds(270, 260, 240, 40);

        login_btn.setBackground(new java.awt.Color(51, 204, 255));
        login_btn.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        login_btn.setText("LOGIN HERE");
        login_btn.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        login_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                login_btnActionPerformed(evt);
            }
        });
        getContentPane().add(login_btn);
        login_btn.setBounds(160, 362, 170, 50);

        jLabel2.setBackground(new java.awt.Color(153, 255, 255));
        getContentPane().add(jLabel2);
        jLabel2.setBounds(0, 0, 580, 550);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void login_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_login_btnActionPerformed
        // TODO add your handling code here:
        String accountant_name=name_tf.getText();
        String pass = password_tf.getText();
        if(accountant_name.equals("") || pass.equals(""))
        {
        JOptionPane.showMessageDialog(this,"All field are required");
        }
        else
        {
             try{
                ResultSet rs = DBLoader.executeSQL("select * from admin where admin ='"+accountant_name+"'and password ='"+pass+"'");
                if(rs.next()){
                    JOptionPane.showMessageDialog(this,"Login successful");
                    
                    name_tf.setText("");
                    password_tf.setText("");
                    Home obj= new Home();
                    obj.setVisible(true);
                    
                    dispose();
                }
                else{
                    JOptionPane.showMessageDialog(this,"Login failed");
                }
            }
            catch(Exception ex){
                ex.printStackTrace();
                JOptionPane.showMessageDialog(this,ex);
                
            }
        }
        
    }//GEN-LAST:event_login_btnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AccountantLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AccountantLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AccountantLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AccountantLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AccountantLogin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JButton login_btn;
    private javax.swing.JLabel name_lbl;
    private javax.swing.JTextField name_tf;
    private javax.swing.JLabel password_lbl;
    private javax.swing.JPasswordField password_tf;
    private javax.swing.JLabel title_lbl;
    // End of variables declaration//GEN-END:variables
}
