
import java.sql.ResultSet;
import javax.swing.JOptionPane;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author HP
 */
public class AddAccountant extends javax.swing.JFrame {

    /**
     * Creates new form AddAccountant
     */
    public AddAccountant() {
        initComponents();
        setSize(800,700);
        setTitle("Add Accountant");
        setLayout(null);
        setVisible(true);
        setDefaultCloseOperation(DISPOSE_ON_CLOSE);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        password_lbl = new javax.swing.JLabel();
        contact_lbl = new javax.swing.JLabel();
        name_lbl = new javax.swing.JLabel();
        email_lbl = new javax.swing.JLabel();
        email_tf = new javax.swing.JTextField();
        contact_tf = new javax.swing.JTextField();
        name_tf = new javax.swing.JTextField();
        password_tf = new javax.swing.JPasswordField();
        addaccount_lbl = new javax.swing.JLabel();
        add_btn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        password_lbl.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        password_lbl.setText("PASSWORD");
        getContentPane().add(password_lbl);
        password_lbl.setBounds(50, 200, 170, 60);

        contact_lbl.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        contact_lbl.setText("CONTACT NUMBER");
        getContentPane().add(contact_lbl);
        contact_lbl.setBounds(50, 340, 170, 60);

        name_lbl.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        name_lbl.setText("NAME");
        getContentPane().add(name_lbl);
        name_lbl.setBounds(50, 140, 170, 60);

        email_lbl.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        email_lbl.setText("E-MAIL");
        getContentPane().add(email_lbl);
        email_lbl.setBounds(50, 270, 110, 60);

        email_tf.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        getContentPane().add(email_tf);
        email_tf.setBounds(310, 280, 300, 40);

        contact_tf.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        contact_tf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                contact_tfActionPerformed(evt);
            }
        });
        getContentPane().add(contact_tf);
        contact_tf.setBounds(310, 350, 300, 40);

        name_tf.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        getContentPane().add(name_tf);
        name_tf.setBounds(310, 150, 300, 40);

        password_tf.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        getContentPane().add(password_tf);
        password_tf.setBounds(310, 210, 300, 40);

        addaccount_lbl.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        addaccount_lbl.setText("ADD ACCOUNTANT SECTION");
        addaccount_lbl.setBorder(new javax.swing.border.MatteBorder(null));
        getContentPane().add(addaccount_lbl);
        addaccount_lbl.setBounds(70, 30, 560, 70);

        add_btn.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        add_btn.setText("ADD ACCOUNTANT");
        add_btn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        add_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                add_btnActionPerformed(evt);
            }
        });
        getContentPane().add(add_btn);
        add_btn.setBounds(170, 440, 240, 40);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void contact_tfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_contact_tfActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_contact_tfActionPerformed

    private void add_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_add_btnActionPerformed
        // TODO add your handling code here:
        String n = name_tf.getText();
        String p = password_tf.getText();
        String mail = email_tf.getText();
        String con = contact_tf.getText();
        
            
            if(n.equals("")|| p.equals("")||mail.equals("")||con.equals(""))
            {
                JOptionPane.showMessageDialog(this,"Every field should be filled");
            }
            else
            {
                try{
                    ResultSet rs = DBLoader.executeSQL("select * from admin where admin ='"+n+"'");
                    if(rs.next()){
                        JOptionPane.showMessageDialog(this,"Accountant Already Exist ");
                        
                    }
                    else{
                        // blankrow created
                        rs.moveToInsertRow();
                        
                        //fill row
                        rs.updateString("admin",n);
                        rs.updateString("password",p);
                        rs.updateString("email", mail);
                        rs.updateString("contact",con);
                        // insert to actual databases
                        rs.insertRow();
                        
                        JOptionPane.showMessageDialog(this,"Accountant added successfully");
                        
                    }
                     name_tf.setText("");
                     password_tf.setText("");
                     email_tf.setText("");
                     contact_tf.setText("");
                }
                catch(Exception ex){
                    ex.printStackTrace();
                    JOptionPane.showMessageDialog(this,ex);
                }
            }
            
    }//GEN-LAST:event_add_btnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AddAccountant.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AddAccountant.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AddAccountant.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AddAccountant.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AddAccountant().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton add_btn;
    private javax.swing.JLabel addaccount_lbl;
    private javax.swing.JLabel contact_lbl;
    private javax.swing.JTextField contact_tf;
    private javax.swing.JLabel email_lbl;
    private javax.swing.JTextField email_tf;
    private javax.swing.JLabel name_lbl;
    private javax.swing.JTextField name_tf;
    private javax.swing.JLabel password_lbl;
    private javax.swing.JPasswordField password_tf;
    // End of variables declaration//GEN-END:variables
}
