public class Admin_section extends javax.swing.JFrame {

    /**
     * Creates new form Admin_section
     */
    public Admin_section() {
        initComponents();
        
        setSize(700,600);
        setTitle("Admin section");
        setLayout(null);
        setDefaultCloseOperation(DISPOSE_ON_CLOSE);
         setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        add_ac_btn = new javax.swing.JButton();
        view_ac_btn = new javax.swing.JButton();
        logout_btn = new javax.swing.JButton();
        admin_lbl = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        add_ac_btn.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        add_ac_btn.setText("ADD ACCOUNTANT");
        add_ac_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                add_ac_btnActionPerformed(evt);
            }
        });
        getContentPane().add(add_ac_btn);
        add_ac_btn.setBounds(220, 150, 250, 60);

        view_ac_btn.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        view_ac_btn.setText("VIEW ACCOUNTANT");
        view_ac_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                view_ac_btnActionPerformed(evt);
            }
        });
        getContentPane().add(view_ac_btn);
        view_ac_btn.setBounds(220, 270, 250, 60);

        logout_btn.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        logout_btn.setText("LOGOUT");
        logout_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logout_btnActionPerformed(evt);
            }
        });
        getContentPane().add(logout_btn);
        logout_btn.setBounds(290, 390, 110, 50);

        admin_lbl.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        admin_lbl.setText("ADMIN SECTION");
        admin_lbl.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        getContentPane().add(admin_lbl);
        admin_lbl.setBounds(200, 30, 330, 60);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void logout_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logout_btnActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_logout_btnActionPerformed

    private void add_ac_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_add_ac_btnActionPerformed
        // TODO add your handling code here:
        AddAccountant obj = new AddAccountant();
        obj.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_add_ac_btnActionPerformed

    private void view_ac_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_view_ac_btnActionPerformed
        // TODO add your handling code here:
        ViewAccountant obj = new ViewAccountant();
        obj.showAccountant();
        obj.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_view_ac_btnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Admin_section.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Admin_section.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Admin_section.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Admin_section.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Admin_section().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton add_ac_btn;
    private javax.swing.JLabel admin_lbl;
    private javax.swing.JButton logout_btn;
    private javax.swing.JButton view_ac_btn;
    // End of variables declaration//GEN-END:variables
}
