
import java.sql.ResultSet;
import javax.swing.JOptionPane;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author HP
 */
public class Admin extends javax.swing.JFrame {

    /**
     * Creates new form Admin_section
     */
    public Admin() {
        initComponents();
        setDefaultCloseOperation(DISPOSE_ON_CLOSE);
        setTitle("ADMIN ");
        setSize(700,500);
        setVisible(true);
        setLayout(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        password_lbl = new javax.swing.JLabel();
        admin_lbl = new javax.swing.JLabel();
        admin_tf = new javax.swing.JTextField();
        Password_tf = new javax.swing.JPasswordField();
        login_btn = new javax.swing.JButton();
        title = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        password_lbl.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        password_lbl.setText("PASSWORD");
        getContentPane().add(password_lbl);
        password_lbl.setBounds(30, 250, 150, 40);

        admin_lbl.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        admin_lbl.setText("ADMIN NAME");
        getContentPane().add(admin_lbl);
        admin_lbl.setBounds(30, 150, 150, 40);

        admin_tf.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        getContentPane().add(admin_tf);
        admin_tf.setBounds(280, 142, 200, 50);

        Password_tf.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        getContentPane().add(Password_tf);
        Password_tf.setBounds(280, 242, 200, 50);

        login_btn.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        login_btn.setText("LOGIN");
        login_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                login_btnActionPerformed(evt);
            }
        });
        getContentPane().add(login_btn);
        login_btn.setBounds(210, 360, 110, 50);

        title.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        title.setText("ADMIN LOGIN");
        title.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        getContentPane().add(title);
        title.setBounds(120, 20, 260, 70);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void login_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_login_btnActionPerformed
        // TODO add your handling code here:
        String adminname = admin_tf.getText();
        String password = Password_tf.getText();
        
        if(adminname.equals("") || password.equals(""))
        {
        JOptionPane.showMessageDialog(this,"All field are required");
        }
        else
        {
             try{
                ResultSet rs = DBLoader.executeSQL("select * from admin where admin ='"+adminname+"'and password ='"+password+"'");
                if(rs.next()){
                    JOptionPane.showMessageDialog(this,"Login successful");
                    
                    admin_tf.setText("");
                    Password_tf.setText("");
                    Admin_section obj= new Admin_section();
                    obj.setVisible(true);
                    
                    dispose();
                }
                else{
                    JOptionPane.showMessageDialog(this,"Login failed");
                }
            }
            catch(Exception ex){
                ex.printStackTrace();
                JOptionPane.showMessageDialog(this,ex);
                
            }
        }
        
        
    }//GEN-LAST:event_login_btnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Admin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPasswordField Password_tf;
    private javax.swing.JLabel admin_lbl;
    private javax.swing.JTextField admin_tf;
    private javax.swing.JButton login_btn;
    private javax.swing.JLabel password_lbl;
    private javax.swing.JLabel title;
    // End of variables declaration//GEN-END:variables
}
