
import java.sql.ResultSet;
import java.util.*;
import javax.swing.*;
import javax.swing.table.AbstractTableModel;
import javax.swing.table.TableModel;


/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author HP
 */
public class EditCourse extends javax.swing.JFrame {
    int ans;
    ArrayList<ECourse> ec;
    mytablemodel tm;
    JTable jt;
    JScrollPane jsp;


    /**
     * Creates new form EditCourse
     */
    public EditCourse() {
        initComponents();
        
        ec = new ArrayList<>();
//        sr.add(new SRecord("abc","afklsdf","klafj"));
        tm = new mytablemodel();
        jt = new JTable();
        jsp =new JScrollPane(jt);
        jt.setModel(tm);
        jsp.setBounds(650,180,800,420);
        add(jsp);
        setRecordToTable();
        
        
        setSize(1900,1100);
        setTitle("EDIT COURSE");
        setDefaultCloseOperation(DISPOSE_ON_CLOSE);
        setVisible(true);
        setLayout(null);
        
    }
     public void setRecordToTable(){
        ec.clear();
        try{
            ResultSet rs = DBLoader.executeSQL("select * from course");
            while(rs.next()){
                String id = rs.getString("id");
                String n = rs.getString("cname");
                String c = rs.getString("cost");
                
                ec.add(new ECourse(id,n,c));
            }
            tm.fireTableDataChanged();
            
        }
        catch(Exception ex){
            
            ex.printStackTrace();
        }
    }
    class mytablemodel extends AbstractTableModel{

        @Override
        public int getRowCount() {
            return ec.size();
        }

        @Override
        public int getColumnCount() {
            return 3;
        }
        @Override
        public String getColumnName(int j) {
            String s[] ={"CourseID","Course Name","Cost of course"};
            return s[j];
        }

        @Override
        public Object getValueAt(int i, int j) {
            ECourse sd = ec.get(i);
            if(j==0)
                return sd.courseid;
            else if(j==1)
                return sd.coursename;
            else
                return sd.cost;
        }
        
    }
    
//    private void jtMouseClicked(java.awt.event.MouseEvent evt) {
//        int rowno  = jt.getSelectedRow();
//        TableModel tm1 = jt.getModel();
//        
//        courseId_tf.setText(tm1.getValueAt(rowno,0).toString());
//        courseName_tf.setText(tm1.getValueAt(rowno,1).toString());
//        coursePrice_tf.setText(tm1.getValueAt(rowno,2).toString());
//        
//    }
//    
   


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        courseName_lbl = new javax.swing.JLabel();
        editCourse_lbl = new javax.swing.JLabel();
        courseId_lbl = new javax.swing.JLabel();
        coursePrice_lbl = new javax.swing.JLabel();
        seprator1 = new javax.swing.JSeparator();
        courseName_tf = new javax.swing.JTextField();
        coursePrice_tf = new javax.swing.JTextField();
        courseId_tf = new javax.swing.JTextField();
        update_btn = new javax.swing.JButton();
        delete_btn = new javax.swing.JButton();
        back_btn = new javax.swing.JButton();
        add_btn = new javax.swing.JButton();
        refresh_btn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jPanel1.setBackground(new java.awt.Color(153, 255, 255));
        jPanel1.setLayout(null);

        courseName_lbl.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        courseName_lbl.setText("Course Name :");
        jPanel1.add(courseName_lbl);
        courseName_lbl.setBounds(50, 320, 130, 50);

        editCourse_lbl.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        editCourse_lbl.setIcon(new javax.swing.ImageIcon("C:\\Users\\HP\\OneDrive\\Documents\\NetBeansProjects\\Fee_management\\src\\feeimages\\edit2.png")); // NOI18N
        editCourse_lbl.setText("EDIT  COURSE  DETAILS");
        jPanel1.add(editCourse_lbl);
        editCourse_lbl.setBounds(30, 50, 550, 90);

        courseId_lbl.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        courseId_lbl.setText("Course ID :");
        jPanel1.add(courseId_lbl);
        courseId_lbl.setBounds(50, 230, 130, 50);

        coursePrice_lbl.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        coursePrice_lbl.setText("Course Price :");
        jPanel1.add(coursePrice_lbl);
        coursePrice_lbl.setBounds(50, 420, 130, 50);

        seprator1.setForeground(new java.awt.Color(0, 0, 0));
        jPanel1.add(seprator1);
        seprator1.setBounds(20, 150, 540, 40);

        courseName_tf.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jPanel1.add(courseName_tf);
        courseName_tf.setBounds(210, 330, 230, 40);

        coursePrice_tf.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jPanel1.add(coursePrice_tf);
        coursePrice_tf.setBounds(210, 420, 230, 40);

        courseId_tf.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jPanel1.add(courseId_tf);
        courseId_tf.setBounds(210, 240, 230, 40);

        update_btn.setBackground(new java.awt.Color(51, 204, 255));
        update_btn.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        update_btn.setIcon(new javax.swing.ImageIcon("C:\\Users\\HP\\OneDrive\\Documents\\NetBeansProjects\\Fee_management\\src\\feeimages\\update.png")); // NOI18N
        update_btn.setText("UPDATE");
        update_btn.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        update_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                update_btnActionPerformed(evt);
            }
        });
        jPanel1.add(update_btn);
        update_btn.setBounds(180, 530, 120, 50);

        delete_btn.setBackground(new java.awt.Color(51, 204, 255));
        delete_btn.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        delete_btn.setIcon(new javax.swing.ImageIcon("C:\\Users\\HP\\OneDrive\\Documents\\NetBeansProjects\\Fee_management\\src\\feeimages\\delete.png")); // NOI18N
        delete_btn.setText("DELETE");
        delete_btn.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        delete_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                delete_btnActionPerformed(evt);
            }
        });
        jPanel1.add(delete_btn);
        delete_btn.setBounds(350, 530, 120, 50);

        back_btn.setBackground(new java.awt.Color(51, 204, 255));
        back_btn.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        back_btn.setIcon(new javax.swing.ImageIcon("C:\\Users\\HP\\OneDrive\\Documents\\NetBeansProjects\\Fee_management\\src\\feeimages\\back1.png")); // NOI18N
        back_btn.setText("BACK");
        back_btn.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        back_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                back_btnActionPerformed(evt);
            }
        });
        jPanel1.add(back_btn);
        back_btn.setBounds(180, 630, 120, 50);

        add_btn.setBackground(new java.awt.Color(51, 204, 255));
        add_btn.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        add_btn.setIcon(new javax.swing.ImageIcon("C:\\Users\\HP\\OneDrive\\Documents\\NetBeansProjects\\Fee_management\\src\\feeimages\\add2.png")); // NOI18N
        add_btn.setText("ADD");
        add_btn.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        add_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                add_btnActionPerformed(evt);
            }
        });
        jPanel1.add(add_btn);
        add_btn.setBounds(30, 530, 120, 50);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 600, 900);

        refresh_btn.setBackground(new java.awt.Color(51, 204, 255));
        refresh_btn.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        refresh_btn.setText("REFRESH");
        refresh_btn.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, null, java.awt.Color.white, null, null));
        refresh_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                refresh_btnActionPerformed(evt);
            }
        });
        getContentPane().add(refresh_btn);
        refresh_btn.setBounds(980, 660, 140, 40);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void add_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_add_btnActionPerformed
        // TODO add your handling code here:

        String cid =courseId_tf.getText();
        String course = courseName_tf.getText() ;
        String cost = (coursePrice_tf.getText());

        if(cid.equals("")|| course.equals("")||cost.equals(""))
        {
            JOptionPane.showMessageDialog(this,"Fill all row madatory!!");
        }
        else
        {
            try{
                ResultSet rs = DBLoader.executeSQL("select * from course where cname ='"+course+"'");
                if(rs.next()){
                    JOptionPane.showMessageDialog(this,"Course Already Exist !!!");

                }
                else{
                    // blankrow created
                    rs.moveToInsertRow();

                    //fill row
                    rs.updateString("cname",course);
                    rs.updateString("cost",cost);
                    //                        rs.updateString("UserName", user);

                    // insert to actual databases
                    rs.insertRow();

                    JOptionPane.showMessageDialog(this,"Course Added successfully");

                }
                courseId_tf.setText("");
                courseName_tf.setText("");
                coursePrice_tf.setText("");

            }
            catch(Exception ex){
                ex.printStackTrace();
                JOptionPane.showMessageDialog(this,ex);
            }
        }
    }//GEN-LAST:event_add_btnActionPerformed

    private void back_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_back_btnActionPerformed
        // TODO add your handling code here:
        Home obj = new Home();
        obj.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_back_btnActionPerformed

    private void update_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_update_btnActionPerformed
        // TODO add your handling code here:
        String cid =courseId_tf.getText();
        String course = courseName_tf.getText() ;
        String cost = (coursePrice_tf.getText());

        if(cid.equals("")||course.equals("")||cost.equals(""))
        {
            JOptionPane.showMessageDialog(this,"All field are mandatory");
        }
        else{
            try
            {
                ResultSet rs = DBLoader.executeSQL("select * from course where id='"+cid+"' ");
                if(rs.next()){

                    rs.updateString("cname",course);
                    rs.updateString("cost",cost);

                    rs.updateRow();
                    JOptionPane.showMessageDialog(this,"course updated successfully");

                    courseId_tf.setText("");
                    courseName_tf.setText("");
                    coursePrice_tf.setText("");
                }
                else{
                    JOptionPane.showMessageDialog(this,"Course id are Not Matched");
                }

            }
            catch(Exception ex){
                ex.printStackTrace();
                JOptionPane.showMessageDialog(this,ex);
            }
        }
    }//GEN-LAST:event_update_btnActionPerformed

    private void delete_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_delete_btnActionPerformed
        // TODO add your handling code here:
        ans = jt.getSelectedRow();
           if(ans== -1){
               JOptionPane.showMessageDialog(this,"Please select correct from Table");
           }
           else{
//               String cat= ct.get(ans).categoryName;
        try
       {
           String acc= ec.get(ans).coursename;
           
           ResultSet rs = DBLoader.executeSQL("select * from course where cname='"+acc+"'");
           
           if(rs.next())
           {
               rs.deleteRow();
               JOptionPane.showMessageDialog(this,"Course deleted succesfully");
           }
           else
           {
               JOptionPane.showMessageDialog(this,"cannnot delete,Course does not exist");
               
           }
           
           
       }
       catch(Exception ex)
       {
           ex.printStackTrace();
           JOptionPane.showMessageDialog(this,ex);
       }
               
           }
              
    }//GEN-LAST:event_delete_btnActionPerformed

    private void refresh_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_refresh_btnActionPerformed
        // TODO add your handling code here:
        setRecordToTable();
    }//GEN-LAST:event_refresh_btnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EditCourse.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EditCourse.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EditCourse.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EditCourse.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EditCourse().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton add_btn;
    private javax.swing.JButton back_btn;
    private javax.swing.JLabel courseId_lbl;
    private javax.swing.JTextField courseId_tf;
    private javax.swing.JLabel courseName_lbl;
    private javax.swing.JTextField courseName_tf;
    private javax.swing.JLabel coursePrice_lbl;
    private javax.swing.JTextField coursePrice_tf;
    private javax.swing.JButton delete_btn;
    private javax.swing.JLabel editCourse_lbl;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton refresh_btn;
    private javax.swing.JSeparator seprator1;
    private javax.swing.JButton update_btn;
    // End of variables declaration//GEN-END:variables
}
