/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author HP
 */
public class Home extends javax.swing.JFrame {

    /**
     * Creates new form Home
     */
    public Home() {
        initComponents();
        setSize(1000,800);
        setTitle("HOME");
        setDefaultCloseOperation(DISPOSE_ON_CLOSE);
        setVisible(true);
        setLayout(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        search_btn = new javax.swing.JButton();
        record_btn = new javax.swing.JButton();
        editcourse_btn = new javax.swing.JButton();
        viewcourse_btn = new javax.swing.JButton();
        about_btn = new javax.swing.JButton();
        addfee_btn = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        change_btn = new javax.swing.JButton();
        exit_btn1 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();

        jPanel1.setBackground(new java.awt.Color(102, 255, 255));
        jPanel1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        search_btn.setBackground(new java.awt.Color(0, 204, 255));
        search_btn.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        search_btn.setIcon(new javax.swing.ImageIcon("C:\\Users\\HP\\OneDrive\\Documents\\NetBeansProjects\\Fee_management\\src\\feeimages\\search-document.png")); // NOI18N
        search_btn.setText("Search Record");
        search_btn.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        search_btn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        search_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                search_btnActionPerformed(evt);
            }
        });
        getContentPane().add(search_btn);
        search_btn.setBounds(330, 170, 310, 130);

        record_btn.setBackground(new java.awt.Color(0, 204, 255));
        record_btn.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        record_btn.setIcon(new javax.swing.ImageIcon("C:\\Users\\HP\\OneDrive\\Documents\\NetBeansProjects\\Fee_management\\src\\feeimages\\view all record.png")); // NOI18N
        record_btn.setText("view all record");
        record_btn.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        record_btn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        record_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                record_btnActionPerformed(evt);
            }
        });
        getContentPane().add(record_btn);
        record_btn.setBounds(680, 170, 290, 130);

        editcourse_btn.setBackground(new java.awt.Color(0, 204, 255));
        editcourse_btn.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        editcourse_btn.setIcon(new javax.swing.ImageIcon("C:\\Users\\HP\\OneDrive\\Documents\\NetBeansProjects\\Fee_management\\src\\feeimages\\edit.png")); // NOI18N
        editcourse_btn.setText("Edit course");
        editcourse_btn.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        editcourse_btn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        editcourse_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editcourse_btnActionPerformed(evt);
            }
        });
        getContentPane().add(editcourse_btn);
        editcourse_btn.setBounds(50, 340, 260, 150);

        viewcourse_btn.setBackground(new java.awt.Color(0, 204, 255));
        viewcourse_btn.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        viewcourse_btn.setIcon(new javax.swing.ImageIcon("C:\\Users\\HP\\OneDrive\\Documents\\NetBeansProjects\\Fee_management\\src\\feeimages\\text-book-opened-from-top-view.png")); // NOI18N
        viewcourse_btn.setText("view course");
        viewcourse_btn.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        viewcourse_btn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        viewcourse_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewcourse_btnActionPerformed(evt);
            }
        });
        getContentPane().add(viewcourse_btn);
        viewcourse_btn.setBounds(330, 340, 310, 150);

        about_btn.setBackground(new java.awt.Color(0, 204, 255));
        about_btn.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        about_btn.setIcon(new javax.swing.ImageIcon("C:\\Users\\HP\\OneDrive\\Documents\\NetBeansProjects\\Fee_management\\src\\feeimages\\about.png")); // NOI18N
        about_btn.setText("About");
        about_btn.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        about_btn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        about_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                about_btnActionPerformed(evt);
            }
        });
        getContentPane().add(about_btn);
        about_btn.setBounds(730, 540, 190, 90);

        addfee_btn.setBackground(new java.awt.Color(0, 204, 255));
        addfee_btn.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        addfee_btn.setIcon(new javax.swing.ImageIcon("C:\\Users\\HP\\OneDrive\\Documents\\NetBeansProjects\\Fee_management\\src\\feeimages\\plus.png")); // NOI18N
        addfee_btn.setText("Add Fees");
        addfee_btn.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        addfee_btn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        addfee_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addfee_btnActionPerformed(evt);
            }
        });
        getContentPane().add(addfee_btn);
        addfee_btn.setBounds(50, 170, 260, 130);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setText("AFFILATED BY :- PTU (PUNJAB TECHNICAL UNIVERSITY) KAPURTHALA");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(90, 60, 820, 40);

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel2.setText("MANAWALA , AMRITSAR , PUNJAB (143109)");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(300, 90, 400, 40);

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel3.setText("AMRITSAR GROUP OF COLLEGES ");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(210, 0, 580, 70);

        change_btn.setBackground(new java.awt.Color(0, 204, 255));
        change_btn.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        change_btn.setIcon(new javax.swing.ImageIcon("C:\\Users\\HP\\OneDrive\\Documents\\NetBeansProjects\\Fee_management\\src\\feeimages\\update.png")); // NOI18N
        change_btn.setText("change password");
        change_btn.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        change_btn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        change_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                change_btnActionPerformed(evt);
            }
        });
        getContentPane().add(change_btn);
        change_btn.setBounds(340, 540, 260, 90);

        exit_btn1.setBackground(new java.awt.Color(0, 204, 255));
        exit_btn1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        exit_btn1.setIcon(new javax.swing.ImageIcon("C:\\Users\\HP\\OneDrive\\Documents\\NetBeansProjects\\Fee_management\\src\\feeimages\\logout.png")); // NOI18N
        exit_btn1.setText("Log out");
        exit_btn1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        exit_btn1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        exit_btn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exit_btn1ActionPerformed(evt);
            }
        });
        getContentPane().add(exit_btn1);
        exit_btn1.setBounds(80, 540, 170, 90);

        jPanel2.setBackground(new java.awt.Color(153, 255, 255));
        getContentPane().add(jPanel2);
        jPanel2.setBounds(0, 0, 1000, 900);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void about_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_about_btnActionPerformed
        // TODO add your handling code here:
        About obj = new About();
        obj.setVisible(true);
    }//GEN-LAST:event_about_btnActionPerformed

    private void change_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_change_btnActionPerformed
        // TODO add your handling code here:
       changePassword obj = new changePassword();
       obj.setVisible(true);
       
    }//GEN-LAST:event_change_btnActionPerformed

    private void exit_btn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exit_btn1ActionPerformed
        // TODO add your handling code here:
         System.exit(0);
    }//GEN-LAST:event_exit_btn1ActionPerformed

    private void addfee_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addfee_btnActionPerformed
        // TODO add your handling code here:
        AddFees obj = new AddFees();
        obj.setVisible(true);
        
        
    }//GEN-LAST:event_addfee_btnActionPerformed

    private void search_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_search_btnActionPerformed
        // TODO add your handling code here:
        SearchRecord obj= new SearchRecord();
        obj.setVisible(true);
        
        
    }//GEN-LAST:event_search_btnActionPerformed

    private void editcourse_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editcourse_btnActionPerformed
        // TODO add your handling code here:
        EditCourse obj = new EditCourse();
        obj.setVisible(true);
        
    }//GEN-LAST:event_editcourse_btnActionPerformed

    private void record_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_record_btnActionPerformed
        // TODO add your handling code here:
       viewAllRecords obj= new viewAllRecords();
       obj.setVisible(true);
       
    }//GEN-LAST:event_record_btnActionPerformed

    private void viewcourse_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewcourse_btnActionPerformed
        // TODO add your handling code here:
        viewCourse obj =new viewCourse();
        obj.setVisible(true);
        
    }//GEN-LAST:event_viewcourse_btnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Home().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton about_btn;
    private javax.swing.JButton addfee_btn;
    private javax.swing.JButton change_btn;
    private javax.swing.JButton editcourse_btn;
    private javax.swing.JButton exit_btn1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JButton record_btn;
    private javax.swing.JButton search_btn;
    private javax.swing.JButton viewcourse_btn;
    // End of variables declaration//GEN-END:variables
}
