
import javax.swing.JOptionPane;
import java.sql.*;


/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author HP
 */
public class login extends javax.swing.JFrame {

    /**
     * Creates new form login
     */
    public login() {
        initComponents();
        setDefaultCloseOperation(DISPOSE_ON_CLOSE);
        setTitle("LOGIN HERE");
        setSize(700,500);
        setVisible(true);
        setLayout(null);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        title = new javax.swing.JLabel();
        user = new javax.swing.JLabel();
        pass = new javax.swing.JLabel();
        user_tf = new javax.swing.JTextField();
        pass_tf = new javax.swing.JPasswordField();
        forget_btn = new javax.swing.JButton();
        login_btn1 = new javax.swing.JButton();
        register_btn1 = new javax.swing.JButton();
        exit_btn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        title.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        title.setText("LOGIN HERE");
        getContentPane().add(title);
        title.setBounds(120, 60, 220, 50);

        user.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        user.setText("USERNAME  :");
        getContentPane().add(user);
        user.setBounds(100, 180, 140, 50);

        pass.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        pass.setText("PASSWORD :");
        getContentPane().add(pass);
        pass.setBounds(100, 260, 130, 50);

        user_tf.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        user_tf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                user_tfActionPerformed(evt);
            }
        });
        getContentPane().add(user_tf);
        user_tf.setBounds(320, 180, 210, 40);

        pass_tf.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        getContentPane().add(pass_tf);
        pass_tf.setBounds(320, 260, 210, 40);

        forget_btn.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        forget_btn.setText("Forget password");
        forget_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                forget_btnActionPerformed(evt);
            }
        });
        getContentPane().add(forget_btn);
        forget_btn.setBounds(470, 390, 180, 40);

        login_btn1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        login_btn1.setText("Login");
        login_btn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                login_btn1ActionPerformed(evt);
            }
        });
        getContentPane().add(login_btn1);
        login_btn1.setBounds(20, 390, 120, 40);

        register_btn1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        register_btn1.setText("Sign up");
        register_btn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                register_btn1ActionPerformed(evt);
            }
        });
        getContentPane().add(register_btn1);
        register_btn1.setBounds(170, 390, 120, 40);

        exit_btn.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        exit_btn.setText("Exit");
        exit_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exit_btnActionPerformed(evt);
            }
        });
        getContentPane().add(exit_btn);
        exit_btn.setBounds(320, 390, 120, 40);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void login_btn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_login_btn1ActionPerformed
        // TODO add your handling code here:
        String username = user_tf.getText();
        String password = pass_tf.getText();
        
        if(username.equals("") || password.equals(""))
        {
        JOptionPane.showMessageDialog(this,"All field are required");
        }
        else
        {
            try{
                ResultSet rs = DBLoader.executeSQL("select * from register where UserName='"+username+"'and Password ='"+password+"'");
                if(rs.next()){
                    JOptionPane.showMessageDialog(this,"Login successful");
                    
                    user_tf.setText("");
                    pass_tf.setText("");
                    UserHome obj= new UserHome();
                    obj.setVisible(true);
                    
                    dispose();
                }
                else{
                    JOptionPane.showMessageDialog(this,"Login failed");
                }
            }
            catch(Exception ex){
                ex.printStackTrace();
                JOptionPane.showMessageDialog(this,ex);
                
            }
            
        }
        
    }//GEN-LAST:event_login_btn1ActionPerformed

    private void user_tfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_user_tfActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_user_tfActionPerformed

    private void forget_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_forget_btnActionPerformed
        // TODO add your handling code here:
        updatePassword ob =new updatePassword();
        ob.setVisible(true);
        dispose();
        
    }//GEN-LAST:event_forget_btnActionPerformed

    private void register_btn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_register_btn1ActionPerformed
        // TODO add your handling code here:
        Register obj = new Register();
        obj.setVisible(true);
        
        dispose();
    }//GEN-LAST:event_register_btn1ActionPerformed

    private void exit_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exit_btnActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_exit_btnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton exit_btn;
    private javax.swing.JButton forget_btn;
    private javax.swing.JButton login_btn1;
    private javax.swing.JLabel pass;
    private javax.swing.JPasswordField pass_tf;
    private javax.swing.JButton register_btn1;
    private javax.swing.JLabel title;
    private javax.swing.JLabel user;
    private javax.swing.JTextField user_tf;
    // End of variables declaration//GEN-END:variables
}
