
import javax.swing.JOptionPane;
import java.sql.*;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author HP
 */
public class Register extends javax.swing.JFrame {

    /**
     * Creates new form Register
     */
    public Register() {
        initComponents();
        setDefaultCloseOperation(DISPOSE_ON_CLOSE);
        setTitle("REGISTER HERE");
        setSize(600,700);
        setLayout(null);
        setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        title_lbl = new javax.swing.JLabel();
        f_name_lbl = new javax.swing.JLabel();
        dob_lbl = new javax.swing.JLabel();
        username_lbl = new javax.swing.JLabel();
        L_name_lbl = new javax.swing.JLabel();
        contact_lbl = new javax.swing.JLabel();
        password_lbl = new javax.swing.JLabel();
        lname_tf = new javax.swing.JTextField();
        username_tf = new javax.swing.JTextField();
        dob_tf = new javax.swing.JTextField();
        contact_tf = new javax.swing.JTextField();
        fname_tf = new javax.swing.JTextField();
        password_tf = new javax.swing.JPasswordField();
        back_btn = new javax.swing.JButton();
        exit_btn = new javax.swing.JButton();
        signup_btn = new javax.swing.JButton();
        signup_btn5 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        title_lbl.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        title_lbl.setText("SIGN UP HERE");
        getContentPane().add(title_lbl);
        title_lbl.setBounds(157, 53, 265, 51);

        f_name_lbl.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        f_name_lbl.setText("FIRST NAME");
        getContentPane().add(f_name_lbl);
        f_name_lbl.setBounds(30, 194, 126, 35);

        dob_lbl.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        dob_lbl.setText("DOB :");
        getContentPane().add(dob_lbl);
        dob_lbl.setBounds(30, 462, 126, 35);

        username_lbl.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        username_lbl.setText("USER NAME");
        getContentPane().add(username_lbl);
        username_lbl.setBounds(30, 321, 126, 35);

        L_name_lbl.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        L_name_lbl.setText("LAST NAME");
        getContentPane().add(L_name_lbl);
        L_name_lbl.setBounds(30, 258, 126, 35);

        contact_lbl.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        contact_lbl.setText("CONTACT NO:");
        getContentPane().add(contact_lbl);
        contact_lbl.setBounds(30, 533, 126, 35);

        password_lbl.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        password_lbl.setText("PASSWORD");
        getContentPane().add(password_lbl);
        password_lbl.setBounds(30, 401, 126, 35);

        lname_tf.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        getContentPane().add(lname_tf);
        lname_tf.setBounds(250, 260, 165, 35);

        username_tf.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        getContentPane().add(username_tf);
        username_tf.setBounds(250, 330, 165, 35);

        dob_tf.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        getContentPane().add(dob_tf);
        dob_tf.setBounds(250, 460, 165, 35);

        contact_tf.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        getContentPane().add(contact_tf);
        contact_tf.setBounds(250, 530, 165, 35);

        fname_tf.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        getContentPane().add(fname_tf);
        fname_tf.setBounds(250, 190, 165, 35);

        password_tf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                password_tfActionPerformed(evt);
            }
        });
        getContentPane().add(password_tf);
        password_tf.setBounds(250, 392, 170, 40);

        back_btn.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        back_btn.setText("Back login");
        back_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                back_btnActionPerformed(evt);
            }
        });
        getContentPane().add(back_btn);
        back_btn.setBounds(220, 600, 150, 40);

        exit_btn.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        exit_btn.setText("Exit");
        exit_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exit_btnActionPerformed(evt);
            }
        });
        getContentPane().add(exit_btn);
        exit_btn.setBounds(410, 600, 100, 40);

        signup_btn.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        signup_btn.setText("Sign Up");
        signup_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                signup_btnActionPerformed(evt);
            }
        });
        getContentPane().add(signup_btn);
        signup_btn.setBounds(50, 602, 140, 40);

        signup_btn5.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        signup_btn5.setText("Sign Up");
        getContentPane().add(signup_btn5);
        signup_btn5.setBounds(50, 602, 140, 40);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void back_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_back_btnActionPerformed
        // TODO add your handling code here:
        login obj = new login();
        obj.setVisible(true);
        dispose();
//        obj.setDefaultCloseOpertion(EXIT_ON_CLOSE);
    }//GEN-LAST:event_back_btnActionPerformed

    private void password_tfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_password_tfActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_password_tfActionPerformed

    private void exit_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exit_btnActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_exit_btnActionPerformed

    private void signup_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_signup_btnActionPerformed
        // TODO add your handling code here:
       
            String fname = fname_tf.getText();
            String lname = lname_tf.getText();
            String user = username_tf.getText();
            String pass = password_tf.getText();
            String dob = dob_tf.getText();
            String contact = contact_tf.getText();
            
            if(fname.equals("")|| lname.equals("")||user.equals("")||pass.equals("")||dob.equals("")||contact.equals(""))
            {
                JOptionPane.showMessageDialog(this,"Every field should be filled");
            }
            else
            {
                try{
                    ResultSet rs = DBLoader.executeSQL("select * from register where UserName ='"+user+"'");
                    if(rs.next()){
                        JOptionPane.showMessageDialog(this,"User Already Exist you can change your password");
                        
                    }
                    else{
                        // blankrow created
                        rs.moveToInsertRow();
                        
                        //fill row
                        rs.updateString("FirstName",fname);
                        rs.updateString("LastName",lname);
                        rs.updateString("UserName", user);
                        rs.updateString("Password",pass);
                        rs.updateString("DOB", dob);
                        rs.updateString("ContactNum",contact);
                        
                        // insert to actual databases
                        rs.insertRow();
                        
                        JOptionPane.showMessageDialog(this,"SignUp successfully");
                        
                    }
                     fname_tf.setText("");
                     lname_tf.setText("");
                     username_tf.setText("");
                     password_tf.setText("");
                     dob_tf.setText("");
                     contact_tf.setText("");
                    
                }
                catch(Exception ex){
                    ex.printStackTrace();
                    JOptionPane.showMessageDialog(this,ex);
                }
            }
            
            
        
        
    }//GEN-LAST:event_signup_btnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Register().setVisible(true);
            }
        });
    }
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel L_name_lbl;
    private javax.swing.JButton back_btn;
    private javax.swing.JLabel contact_lbl;
    private javax.swing.JTextField contact_tf;
    private javax.swing.JLabel dob_lbl;
    private javax.swing.JTextField dob_tf;
    private javax.swing.JButton exit_btn;
    private javax.swing.JLabel f_name_lbl;
    private javax.swing.JTextField fname_tf;
    private javax.swing.JTextField lname_tf;
    private javax.swing.JLabel password_lbl;
    private javax.swing.JPasswordField password_tf;
    private javax.swing.JButton signup_btn;
    private javax.swing.JButton signup_btn5;
    private javax.swing.JLabel title_lbl;
    private javax.swing.JLabel username_lbl;
    private javax.swing.JTextField username_tf;
    // End of variables declaration//GEN-END:variables
}
