
import java.sql.ResultSet;
import java.util.ArrayList;
import javax.swing.JScrollPane;
import javax.swing.JTable;
import javax.swing.table.AbstractTableModel;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author HP
 */
public class userSearchRecord extends javax.swing.JFrame {
    
    ArrayList<SRecord> sr;
    mytablemodel tm;
    JTable jt;
    JScrollPane jsp;

    /**
     * Creates new form userSearchRecord
     */
    public userSearchRecord() {
        initComponents();
        
        sr = new ArrayList<>();
//        sr.add(new SRecord("abc","afklsdf","klafj"));
        tm = new mytablemodel();
        jt = new JTable();
        jsp =new JScrollPane(jt);
        jt.setModel(tm);
        jsp.setBounds(100,160,1290,620);
        add(jsp);
        
        setSize(1900,1100);
        setTitle("SEARCH RECORD");
        setDefaultCloseOperation(DISPOSE_ON_CLOSE);
        setVisible(true);
        setLayout(null);
        setRecordToTable();
    }
    
    class mytablemodel extends AbstractTableModel{

        @Override
        public int getRowCount() {
            return sr.size();
        }

        @Override
        public int getColumnCount() {
            return 6;
        }
        @Override
        public String getColumnName(int j) {
            String s[] ={"ReceiptNo","StudentName","Payment Mode","Course","Amount","Remarks"};
            return s[j];
        }

        @Override
        public Object getValueAt(int i, int j) {
            SRecord sd = sr.get(i);
            if(j==0)
                return sd.receiptNo;
            else if(j==1)
                return sd.studentName;
            else if(j==2)
                return sd.paymentMode;
            else if(j==3)
                return sd.course;
            else if(j==4)
                return sd.amount;
            else
                return sd.remark;
        }
        
    }
    public void setRecordToTable(){
        sr.clear();
        try{
            ResultSet rs = DBLoader.executeSQL("select * from feedetails");
            while(rs.next()){
                String rec = rs.getString("receiptNo");
                String stud = rs.getString("studentName");
                String pay = rs.getString("payment_mode");
                String cors = rs.getString("courseName");
                String amt = rs.getString("totalAmount");
                String rem  = rs.getString("remarks");
                
                sr.add(new SRecord(rec,stud,pay,cors,amt,rem));
            }
            tm.fireTableDataChanged();
            
        }
        catch(Exception ex){
            
            ex.printStackTrace();
        }
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        search_tf = new javax.swing.JTextField();
        search_btn = new javax.swing.JButton();
        name_lbl = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        search_tf.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        getContentPane().add(search_tf);
        search_tf.setBounds(500, 60, 280, 40);

        search_btn.setBackground(new java.awt.Color(0, 204, 255));
        search_btn.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        search_btn.setText("SEARCH");
        search_btn.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        search_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                search_btnActionPerformed(evt);
            }
        });
        getContentPane().add(search_btn);
        search_btn.setBounds(815, 62, 120, 40);

        name_lbl.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        name_lbl.setText("ENTER THE NAME OF STUDENT :");
        getContentPane().add(name_lbl);
        name_lbl.setBounds(120, 60, 300, 40);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void search_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_search_btnActionPerformed
        // TODO add your handling code here:
        sr.clear();
         String search = (String)search_tf.getText();
        try{
            
            ResultSet rs = DBLoader.executeSQL("select * from feedetails where studentName='"+search+"'");
            while(rs.next()){
                String rec = rs.getString("receiptNo");
                String stud = rs.getString("studentName");
                String pay = rs.getString("payment_mode");
                String cors = rs.getString("courseName");
                String amt = rs.getString("totalAmount");
                String rem  = rs.getString("remarks");
                
                sr.add(new SRecord(rec,stud,pay,cors,amt,rem));
            }
            tm.fireTableDataChanged();
            
        }
        catch(Exception ex){
            
            ex.printStackTrace();
        }
    }//GEN-LAST:event_search_btnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(userSearchRecord.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(userSearchRecord.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(userSearchRecord.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(userSearchRecord.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new userSearchRecord().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel name_lbl;
    private javax.swing.JButton search_btn;
    private javax.swing.JTextField search_tf;
    // End of variables declaration//GEN-END:variables
}
