
import java.sql.ResultSet;
import java.util.ArrayList;
import javax.swing.JScrollPane;
import javax.swing.JTable;
import javax.swing.table.AbstractTableModel;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author HP
 */
public class viewAllRecords extends javax.swing.JFrame {
    ArrayList<viewAll> vr;
    mytablemodel tm;
    JTable jt;
    JScrollPane jsp;

    /**
     * Creates new form viewAllRecords
     */
    public viewAllRecords() {
        initComponents();
        
        vr = new ArrayList<>();
//        sr.add(new SRecord("abc","afklsdf","klafj"));
        tm = new mytablemodel();
        jt = new JTable();
        jsp =new JScrollPane(jt);
        jt.setModel(tm);
        jsp.setBounds(30,60,1470,700);
        add(jsp);
        
        setRecordToTable();
        
        setSize(1900,1100);
        setTitle("VIEW ALL RECORDS");
        setDefaultCloseOperation(DISPOSE_ON_CLOSE);
        setVisible(true);
        setLayout(null);
    }
    
    class mytablemodel extends AbstractTableModel{

        @Override
        public int getRowCount() {
            return vr.size();
        }

        @Override
        public int getColumnCount() {
            return 12;
        }
        @Override
        public String getColumnName(int j) {
            String s[] ={"ReceiptNo","StudentName","Payment Mode","Course","Amount","Rollno","BankName","GSTNo","CGST","SGST","START YEAR","LAST YEAR","Remarks"};
            return s[j];
        }

        @Override
        public Object getValueAt(int i, int j) {
            viewAll sd = vr.get(i);
            if(j==0)
                return sd.receiptNo;
            else if(j==1)
                return sd.studentName;
            else if(j==2)
                return sd.paymentMode;
            else if(j==3)
                return sd.course;
            else if(j==4)
                return sd.amount;
            else if(j==5)
                return sd.rollno;
            else if(j==6)
                return sd.bankname;
            else if(j==7)
                return sd.gst;
            else if(j==8)
                return sd.cgst;
            else if(j==9)
                return sd.sgst;
            else if(j==10)
                return sd.year1;
            else if(j==11)
                return sd.year2;
            else
                return sd.remark;
        }
        
    }
    public void setRecordToTable(){
        vr.clear();
        try{
            ResultSet rs = DBLoader.executeSQL("select * from feedetails");
            while(rs.next()){
                String rec = rs.getString("receiptNo");
                String stud = rs.getString("studentName");
                String pay = rs.getString("payment_mode");
                String cors = rs.getString("courseName");
                String amt = rs.getString("totalAmount");
                String roll = rs.getString("Rollno");
                String bank = rs.getString("bankname");
                String gst = rs.getString("gstno");
                String cgst = rs.getString("cgst");
                String sgst = rs.getString("sgst");
                String y1 = rs.getString("year1");
                String y2 = rs.getString("year2");
                String rem  = rs.getString("remarks");
                
                vr.add(new viewAll(rec,stud,pay,cors,amt,roll,bank,cgst,sgst,y1,y2,gst,rem));
            }
            tm.fireTableDataChanged();
            
        }
        catch(Exception ex){
            
            ex.printStackTrace();
        }
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(viewAllRecords.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(viewAllRecords.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(viewAllRecords.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(viewAllRecords.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new viewAllRecords().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
