
import java.sql.ResultSet;
import java.util.ArrayList;
import javax.swing.JScrollPane;
import javax.swing.JTable;
import javax.swing.table.AbstractTableModel;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author HP
 */
public class viewCourse extends javax.swing.JFrame {
    ArrayList<vcourse> vc;
    mytablemodel tm;
    JTable jt;
    JScrollPane jsp;

    /**
     * Creates new form viewCourse
     */
    public viewCourse() {
        initComponents();
        
        vc = new ArrayList<>();
//        sr.add(new SRecord("abc","afklsdf","klafj"));
        tm = new mytablemodel();
        jt = new JTable();
        jsp =new JScrollPane(jt);
        jt.setModel(tm);
        jsp.setBounds(50,50,1400,720);
        add(jsp);
        setRecordToTable();
        
        
        setSize(1900,1100);
        setTitle("VIEW COURSE");
        setDefaultCloseOperation(DISPOSE_ON_CLOSE);
        setVisible(true);
        setLayout(null);
    }
    
    class mytablemodel extends AbstractTableModel {

        @Override
        public int getRowCount() {
            return vc.size();
        }

        @Override
        public int getColumnCount() {
            return 3;
        }

        @Override
        public String getColumnName(int j) {
            String s[] = {"ID", "COURSE NAME ", "PRICE OF THE COURSE"};
            return s[j];
        }

        @Override
        public Object getValueAt(int i, int j) {
            vcourse sd = vc.get(i);
            if (j == 0) {
                return sd.id;
            }
            else if (j == 1) {
                return sd.coursename;
            } 
            else {
                return sd.cost;
            }
        }

    }

    public void setRecordToTable() {
        vc.clear();
        try {
            ResultSet rs = DBLoader.executeSQL("select * from course");
            while (rs.next()) {
                String id = rs.getString("id");
                String cn = rs.getString("cname");
                String cost = rs.getString("cost");
               
                vc.add(new vcourse(id, cn, cost));
            }
            tm.fireTableDataChanged();

        } catch (Exception ex) {

            ex.printStackTrace();
        }
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(viewCourse.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(viewCourse.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(viewCourse.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(viewCourse.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new viewCourse().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
